# Generated by Django 4.2.3 on 2023-08-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=256)),
                ('last_session', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
