# Generated by Django 4.2.4 on 2023-08-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=128, upload_to='')),
            ],
        ),
    ]
