# Generated by Django 2.2.12 on 2022-08-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bingo',
            fields=[
                ('idBingo', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('cantidad_bingos', models.PositiveIntegerField()),
                ('fecha_sorteo', models.DateField()),
                ('contador_consultas', models.PositiveIntegerField()),
                ('nombre_bingo', models.CharField(max_length=128)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('idVisita', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('fyh_visita', models.DateTimeField()),
                ('ip', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Carton',
            fields=[
                ('idCarton', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('num_carton', models.PositiveIntegerField()),
                ('vendido', models.BooleanField(default=True)),
                ('idBingo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bingos.Bingo')),
            ],
        ),
    ]
