# Generated by Django 4.2.4 on 2023-08-11 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bingos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bingo',
            old_name='cantidad_bingos',
            new_name='cantidad_cartones',
        ),
    ]
