# Generated by Django 4.2.4 on 2023-08-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bingos', '0002_rename_cantidad_bingos_bingo_cantidad_cartones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bingo',
            name='nombre_bingo',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
