# Generated by Django 4.2.3 on 2023-08-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=128)),
                ('descripcion', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=10)),
                ('imagen', models.CharField(max_length=256)),
                ('link', models.CharField(max_length=256)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
    ]
