# Generated by Django 4.2.4 on 2023-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0004_alter_publicidad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='imagen',
            field=models.ImageField(max_length=256, upload_to=''),
        ),
    ]
