# Generated by Django 4.2.4 on 2023-08-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicidad', '0005_alter_publicidad_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicidad',
            name='empresa',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
